### ISSUE TITLE
How to Configure APM Agent to work

### ISSUE THREAD

**Issue by Haddad1** [philkra/elastic-apm-php-agent#106]
Hey i asked a prev question but for some reason it was closed before i got an answer, 

i just want to know how to configure the PHP APM Agent to send the data/stats to the APM Server. This is what i have for the config but its not working, but i cant see anything in my ELK Server (whichhas APM installed and enabled).

`<?php
require 'vendor/autoload.php';

$config = [
    'appName'     => 'APM Test Server',
    'appVersion'  => '1.0',
    'serverUrl'   => 'http://172.31.24.70:5066',
    'hostname'    => 'APM Test Server',
    'env'         => ['DOCUMENT_ROOT'],
];
$agent = new PhilKra\Agent($config);
echo "hello";
sleep(5);
echo "goodbye";
?>`

am i doing anything wrong here?

thank you

**Comment by philkra** [comment]
I closed because, I provided you the answer. I can not give you answer, there are to many unknowns on your setup. Please refer to the getting started with apm server in the official documentation and use this lib's examples to narrow in your scope. Closing this issue as well as with same reasoning of #104

**Comment by Haddad1** [comment]
ok what do you require from my end to help me?
