### ISSUE TITLE
Span context

### ISSUE THREAD

**Issue by cosmorogers** [philkra/elastic-apm-php-agent#116]
Hello

Just wondering why the `PhilKra\Events\Span` object uses `context`, (https://github.com/philkra/elastic-apm-php-agent/blob/master/src/Events/Span.php#L46) where as the base `PhilKra\Events\EventBean` uses `contexts` (https://github.com/philkra/elastic-apm-php-agent/blob/master/src/Events/EventBean.php#L67)

This means that if I try and set some tags on my span, eg `$span->setTags(['foo' => 'bar']);` they do not actually get sent to the Elastic APM agent, as when the Span is serialized it uses `context`, rather than `$this->getContext()`.
https://github.com/philkra/elastic-apm-php-agent/blob/master/src/Events/Span.php#L159
https://github.com/philkra/elastic-apm-php-agent/blob/master/src/Events/Transaction.php#L148

Not sure if this is a bug, or deliberate? 

Perhaps if the Span object is not meant to set tags, then `setTags` should be moved to a different object / trait?

When you open a span in Kibana, it seems to support tags?
![image](https://user-images.githubusercontent.com/3998761/69816213-da90cc80-11ef-11ea-9a05-fce6eca26bbe.png)

**Comment by philkra** [comment]
Hi, this is a bug, great catch! `spans` is simply not serialized in the event. I'll fix that soon. I ping you in the PR. Thanks for reporting 💪

**Comment by philkra** [comment]
I stand corrected, this works as expected. `tags` is correctly nested in `context`. Would you mind using the _View span in Discover_ functionality of APM UI to determine if the field is populated?

**Comment by arkaitzgarro** [comment]
Hi,

I see that you made the change to use `$this->getContext()` when serializing `PhilKra\Events\Span` objects, but this class still keeps a `$context` property.

As far I can see, [setting the context](https://github.com/philkra/elastic-apm-php-agent/blob/master/src/Events/Span.php#L127L130) for a `Span` it's useless since the variable it's not used, and the context will be lost (correct me if I'm wrong).

Should we do something like that instead, at `PhilKra\Events\EventBean` level?

```php
/**
 * Provide additional Context to the Span
 *
 * @link https://www.elastic.co/guide/en/apm/server/master/span-api.html
 *
 * @param array $context
 */
public function addContext(array $context = [])
{
    $this->contexts = array_merge($this->contexts, $context);
}
```
