### ISSUE TITLE
Can't connect to apm-agent version 7.3.1

### ISSUE THREAD

**Issue by muhammadazril** [philkra/elastic-apm-php-agent#140]
when i try to connect in file token.php

use \PhilKra\Agent;
function createToken() {
        $config = [
            'appName'     => 'testapp',
            'appVersion'  => '1.0',
            'serverUrl'   => 'http://apm-server:8200',
        ];
        $agent = new \PhilKra\Agent($config);
        $transaction = $agent->startTransaction('POST api/v1/token/create');
        \Log::info("isi apm", [
            "config" => $config,
            "agent" => $agent,
            "transaction_name" => $transaction->getTransactionName(),
        ]);
// do some command
        $agent->stopTransaction($transaction->getTransactionName());
        return $this->Response();
}

then in kibana, check apm-agent status. It says No data has been received from agents yet

**Comment by dstepe** [comment]
First, there isn't any activity on this project at this point. You might try the new package being put together based on this work. https://github.com/nipwaayoni/elastic-apm-php-agent

Second, is your APM server really accessible as `apm-server`? Can you run a simple curl POST operation and get a valid http response from that server and port?

Third, I don't see that you are explicitly calling `$agent->send()`. While the latest code in this package includes an `Agent::__destruct()` method that calls send, that makes find errors in the send method very difficult. You should at least call it yourself and test the response value. It will be a boolean true if the agent was able to send the data, false otherwise. The new package referenced above has some other things you can do to further investigate the send response.

**Comment by muhammadazril** [comment]
> when i try to connect in file token.php
> 
> use \PhilKra\Agent;
> function createToken() {
> $config = [
> 'appName' => 'testapp',
> 'appVersion' => '1.0',
> 'serverUrl' => 'http://apm-server:8200',
> ];
> $agent = new \PhilKra\Agent($config);
> $transaction = $agent->startTransaction('POST api/v1/token/create');
> \Log::info("isi apm", [
> "config" => $config,
> "agent" => $agent,
> "transaction_name" => $transaction->getTransactionName(),
> ]);
> // do some command
> $agent->stopTransaction($transaction->getTransactionName());
> return $this->Response();
> }
> 
> then in kibana, check apm-agent status. It says No data has been received from agents yet

I update my comment up there.
my APM server accessible as apm-server in kibana check APM server status.
when i use $agent->send() got response 500. But when i use my code on the top comment my function, Response 200 but apm-server didn't recieve data from agent

**Comment by science695** [comment]
@muhammadazril the 7.0 version of this package does not work with the V2 of the intake api.

This package's 7.0.3 beta version seems to be working well enough to be production ready.

However, the maintainer of this package has switched all of his efforts over to making an elastic official php agent with php extension.

**Comment by muhammadazril** [comment]
> @muhammadazril the 7.0 version of this package does not work with the V2 of the intake api.
> 
> This package's 7.0.3 beta version seems to be working well enough to be production ready.
> 
> However, the maintainer of this package has switched all of his efforts over to making an elastic official php agent with php extension.

Thank you @ science695 @dstepe now, I use package https://github.com/nipwaayoni/elastic-apm-php-agent 7.1 in my file.php, with command $agent->send() after $agent->stopTransaction($transaction->getTransactionName());
