### ISSUE TITLE
Add custom span detail

### ISSUE THREAD

**Issue by Geenensq** [philkra/elastic-apm-php-agent#53]
Hello , 

I need to monitor my web services calls.
It seems to me that we have to use spans? Can you confirm it?

And how can I do it if it is?

I use your libraries (elastic-apm-php-agent & elastic-apm-laravel)

Thank you !

**Comment by philkra** [comment]
@Geenensq , well it depends to what level of granularity you want to monitor your web service. 

What do you want to achieve? 
Have you given the agent and the laravel provider a try?

**Comment by Geenensq** [comment]
@philkra Thank you for your answer. 
I wish I could have the response times of the webservices that I ask.
For the moment I have not tried anything

**Comment by dstepe** [comment]
I implemented this library for our own web services for exactly the same reason. I started by simply instantiating the agent, starting the transaction and then sending it. Spans are not required to simply get the overall time. You can add them later to get detail within the transaction.

If you are using the Laravel package as well, it handles much of this for you. Are the web services you want to monitor in Laravel?

**Comment by philkra** [comment]
@Geenensq could the explanation of @dstepe help you solve this?

**Comment by Geenensq** [comment]
@philkra 

No Unfortunately.
I think I did not speak well.
I need to have response times when my API queries external webservices with CURL.

**Comment by dstepe** [comment]
@Geenensq It sounds like you actually need a feature enhancement in the Laravel package (https://github.com/philkra/elastic-apm-laravel). While this package used by the Laravel package, the Laravel package is responsible to capturing and setting spans on the transaction. It can already capture the database queries as spans because Laravel provides a mechanism for hooking queries. You're asking for something similar on arbitrary code execution.

Does that sound right?

**Comment by philkra** [comment]
Please Check in the added example in the readme is helpfull to what you want to achieve 
https://github.com/philkra/elastic-apm-php-agent#example-of-a-transaction

**Comment by philkra** [comment]
closing due no feedback
