### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by philkra** [philkra/elastic-apm-php-agent#55]
> We are experiencing an issue when reporting to APM from our laravel app.

```
POST https://APP_ID.apm.eu-central-1.aws.cloud.es.io/v1/transactions` resulted in a `413 Request Entity Too Large`
```

I see there's an config option for limiting the `backtraceDepth`, but can I be sure that limiting this is sufficient?

https://github.com/philkra/elastic-apm-laravel/issues/36

/cc @Froelund

**Comment by dstepe** [comment]
It looks like the `backtraceDepth` option is only used when capturing query traces:

https://github.com/philkra/elastic-apm-laravel/blob/master/src/Providers/ElasticApmServiceProvider.php#L152

That's something specific to the Laravel module which generates it's own query spans and has the opportunity to influence the depth. I'm not sure how that option would be applied in this package since traces aren't generated here.

**Comment by philkra** [comment]
oh wow, I missed that! Yet, every transaction generates a `debug_backtrace` as well, so that should be some configurable value.

**Comment by dstepe** [comment]
Yeah. I think truly mitigating the total size issue will require coordination in both modules. It's also possible that large stack traces are generated outside of the control of either package, including in the `catchThrowable` method since it has the exception, with stack trace, handed to it.

**Comment by philkra** [comment]
This is can now be configured with Release ˋv6.5.4ˋ
