### ISSUE TITLE
PHP version question

### ISSUE THREAD

**Issue by gschwel** [philkra/elastic-apm-php-agent#58]
Will this agent work with an older version of php, such as 5.3.10?

**Comment by philkra** [comment]
no, sorry it will not, the min version is `7.0`, I saw some forks of this repo (a while back) that ensured support for `5.6.x`. 

As a side note: holy guacamole `5.3.10` !!! you should seriously consider upgrading your app to `7.x`, see the supported versions timeline: http://php.net/supported-versions.php

**Comment by gschwel** [comment]
Thank you, that's what I thought. Ha, yes, that's my next conversation, is how much effort will it take to get on 7.0. Thanks again for the quick response, much appreciated.

**Comment by philkra** [comment]
You‘re very welcome! Good luck with the migration, I recommend this [link](
https://www.reddit.com/r/PHP/comments/3veusf/how_can_i_check_a_large_php5_codebase_for_php7/) there compabilty checkers mentioned that helped back when we migrated

**Comment by gregfr** [comment]
Is the min version still 7.0? I'm on 7.0.33 and I have this error:
```
syntax error, unexpected '?', expecting variable (T_VARIABLE) in /vendor/philkra/elastic-apm-php-agent/src/Agent.php on line 221
```

**Comment by dstepe** [comment]
You can see in the `composer.json` that the minimum PHP version is not 7.1:

https://github.com/philkra/elastic-apm-php-agent/blob/master/composer.json#L6

I'm surprised composer would install it if you are running under 7.0.x.

This package, and the new package based on it (https://github.com/nipwaayoni/elastic-apm-php-agent) are requiring higher versions of PHP to take advantage of new language features. All support, including security updates, ended for 7.0 at the start of 2019 (https://www.php.net/supported-versions.php). If there is any way possible, I would strongly encourage you to update for that reason and because more packages will require higher versions.
