### ISSUE TITLE
nested span

### ISSUE THREAD

**Issue by calvera** [philkra/elastic-apm-php-agent#70]
hi, does someone have working example of nested spans?

thanks

-ks-

**Comment by philkra** [comment]
Not yet! I'm working on more examples, bear with me. I'll put it on the TODO list

**Comment by dstepe** [comment]
@calvera I wanted to respond to this sooner, but have been tied up in other work. I don't think that APM really has a concept of "nested spans". A span is created a by start and duration within a transaction., The start attribute is defined by the schema as:

```
Offset relative to the transaction's timestamp identifying the start of the span, in milliseconds
```

And the duration as:

```
Duration of the span in milliseconds
```

When the transaction is visualized, spans are ordered by their offset from the transactions start time.

So you don't really create "nested spans", you simply create a span with an offset from the start of the containing transaction.

**Comment by calvera** [comment]
i'm not sure if it applies:

Spans have a transaction.id attribute that refers to their parent transaction. They also have a parent.id attribute that refers to their parent span, or their transaction.

**Comment by dstepe** [comment]
This probably requires additional investigation. I know that with APM schema v1, I am creating multiple spans in a single transaction which can be considered "nested" and visualize the way I expect. I've only done basic schema validation against v2, but I did not think there was a major change.

This may just be a "degree of correctness" rather than a requirement.
